apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      component: {{ .Values.postgres.name }}
  template:
    metadata:
      labels:
        component: {{ .Values.postgres.name }}
    spec:
      volumes:
        - name: {{ .Values.postgres.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.postgres.volume.pvc.name }}
      containers:
        - name: {{ .Values.postgres.name }}
          image: {{ .Values.postgres.container.image }}
          ports:
            - containerPort: {{ .Values.postgres.container.port }}
          volumeMounts:
            - name: {{ .Values.postgres.volume.name }}
              mountPath: {{ .Values.postgres.volume.mountPath }}
              subPath: {{ .Values.postgres.volume.subPath }}
          envFrom:
            - configMapRef:
                name: {{ .Values.postgres.config.name }}
