apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.name }}
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    component: {{ .Values.postgres.name }}
  ports:
    - port: {{ .Values.postgres.service.port }}
      targetPort: {{ .Values.postgres.service.port }}